# Generated by Django 3.1.2 on 2020-11-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2083, null=True)),
                ('seeders', models.IntegerField(default=0)),
                ('leechers', models.IntegerField(default=0)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('magnet', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
