# Generated by Django 3.1.2 on 2020-11-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdbClone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrent',
            name='leechers',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='magnet',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='seeders',
        ),
        migrations.RemoveField(
            model_name='torrent',
            name='size',
        ),
        migrations.AddField(
            model_name='torrent',
            name='imdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Magnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2083)),
                ('seeders', models.IntegerField(default=0)),
                ('leechers', models.IntegerField(default=0)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('magnet', models.TextField(blank=True, null=True)),
                ('imdb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torrent_magnet', to='imdbClone.torrent')),
            ],
        ),
    ]
