# Generated by Django 3.1.2 on 2020-11-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdbClone', '0005_auto_20201126_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torrent',
            options={'ordering': ['-added_on']},
        ),
    ]
