# Generated by Django 3.1.2 on 2020-11-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbClone', '0006_auto_20201127_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='casts',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
