# Generated by Django 3.1.2 on 2020-11-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdbClone', '0007_auto_20201127_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torrent',
            name='casts',
            field=models.TextField(null=True),
        ),
    ]
